///hg_del_vertex_arrays()
/*

 Underlying HG script.

*/

global.HG_VERTEX_SCALE=-1;
global.HG_VERTEX_TYPE=-1;

//FULL (BOX):
global.HG_VERTEX_X_FULL=0;
global.HG_VERTEX_Y_FULL=0;

//SLOPE LEFT:
global.HG_VERTEX_X_SLOPELEFT=0;
global.HG_VERTEX_Y_SLOPELEFT=0;

//SLOPE RIGHT:
global.HG_VERTEX_X_SLOPERIGHT=0;
global.HG_VERTEX_Y_SLOPERIGHT=0;

//SLOPE TOPLEFT:
global.HG_VERTEX_X_SLOPETOPLEFT=0;
global.HG_VERTEX_Y_SLOPETOPLEFT=0;

//SLOPE TOPRIGHT:
global.HG_VERTEX_X_SLOPETOPRIGHT=0;
global.HG_VERTEX_Y_SLOPETOPRIGHT=0;

//SLAB BOTTOM:
global.HG_VERTEX_X_SLABBOTTOM=0;
global.HG_VERTEX_Y_SLABBOTTOM=0;

//SLAB TOP:
global.HG_VERTEX_X_SLABTOP=0;
global.HG_VERTEX_Y_SLABTOP=0;

//SLAB LEFT:
global.HG_VERTEX_X_SLABLEFT=0;
global.HG_VERTEX_Y_SLABLEFT=0;

//SLAB RIGHT:
global.HG_VERTEX_X_SLABRIGHT=0;
global.HG_VERTEX_Y_SLABRIGHT=0;

//SLOPE SMALL LEFT:
global.HG_VERTEX_X_SLOPESMLEFT=0;
global.HG_VERTEX_Y_SLOPESMLEFT=0;

//SLOPE SMALL RIGHT:
global.HG_VERTEX_X_SLOPESMRIGHT=0;
global.HG_VERTEX_Y_SLOPESMRIGHT=0;

//SLOPE SMALL TOPLEFT:
global.HG_VERTEX_X_SLOPESMTOPLEFT=0;
global.HG_VERTEX_Y_SLOPESMTOPLEFT=0;

//SLOPE SMALL TOPRIGHT:
global.HG_VERTEX_X_SLOPESMTOPRIGHT=0;
global.HG_VERTEX_Y_SLOPESMTOPRIGHT=0;

//SLOPE SMALL ELEV LEFT:
global.HG_VERTEX_X_SLOPESMELEVLEFT=0;
global.HG_VERTEX_Y_SLOPESMELEVLEFT=0;

//SLOPE SMALL ELEV RIGHT:
global.HG_VERTEX_X_SLOPESMELEVRIGHT=0;
global.HG_VERTEX_Y_SLOPESMELEVRIGHT=0;

//SLOPE SMALL ELEV TOPLEFT:
global.HG_VERTEX_X_SLOPESMELEVTOPLEFT=0;
global.HG_VERTEX_Y_SLOPESMELEVTOPLEFT=0;

//SLOPE SMALL ELEV TOPRIGHT:
global.HG_VERTEX_X_SLOPESMELEVTOPRIGHT=0;
global.HG_VERTEX_Y_SLOPESMELEVTOPRIGHT=0;





