///hg_set_vertex_arrays_ext(Multiplier)
/*

 Underlying HG script.

*/
var m;

m=argument0;
global.HG_VERTEX_SCALE=m;
global.HG_VERTEX_TYPE=1;

m*=0.5;

//FULL (BOX):
global.HG_VERTEX_X_FULL[0]=-1*m;
global.HG_VERTEX_X_FULL[1]=+0*m;
global.HG_VERTEX_X_FULL[2]=+1*m;
global.HG_VERTEX_X_FULL[3]=+1*m;
global.HG_VERTEX_X_FULL[4]=+1*m;
global.HG_VERTEX_X_FULL[5]=+0*m;
global.HG_VERTEX_X_FULL[6]=-1*m;
global.HG_VERTEX_X_FULL[7]=-1*m;

global.HG_VERTEX_Y_FULL[0]=+1*m;
global.HG_VERTEX_Y_FULL[1]=+1*m;
global.HG_VERTEX_Y_FULL[2]=+1*m;
global.HG_VERTEX_Y_FULL[3]=+0*m;
global.HG_VERTEX_Y_FULL[4]=-1*m;
global.HG_VERTEX_Y_FULL[5]=-1*m;
global.HG_VERTEX_Y_FULL[6]=-1*m;
global.HG_VERTEX_Y_FULL[7]=+0*m;

//CIRCLE (PSEUDO):
global.HG_VERTEX_X_CIRCLE[0]=+0*m;
global.HG_VERTEX_X_CIRCLE[1]=-1*m;
global.HG_VERTEX_X_CIRCLE[2]=+0*m;
global.HG_VERTEX_X_CIRCLE[3]=+1*m;

global.HG_VERTEX_Y_CIRCLE[0]=-1*m;
global.HG_VERTEX_Y_CIRCLE[1]=+0*m;
global.HG_VERTEX_Y_CIRCLE[2]=+1*m;
global.HG_VERTEX_Y_CIRCLE[3]=+0*m;

//SLOPE LEFT:
global.HG_VERTEX_X_SLOPELEFT[0]=-1*m;
global.HG_VERTEX_X_SLOPELEFT[1]=-1*m;
global.HG_VERTEX_X_SLOPELEFT[2]=-1*m;
global.HG_VERTEX_X_SLOPELEFT[3]=+0*m;
global.HG_VERTEX_X_SLOPELEFT[4]=+1*m;
global.HG_VERTEX_X_SLOPELEFT[5]=+0*m;

global.HG_VERTEX_Y_SLOPELEFT[0]=-1*m;
global.HG_VERTEX_Y_SLOPELEFT[1]=+0*m;
global.HG_VERTEX_Y_SLOPELEFT[2]=+1*m;
global.HG_VERTEX_Y_SLOPELEFT[3]=+1*m;
global.HG_VERTEX_Y_SLOPELEFT[4]=+1*m;
global.HG_VERTEX_Y_SLOPELEFT[5]=+0*m;

//SLOPE RIGHT:
global.HG_VERTEX_X_SLOPERIGHT[0]=-1*m;
global.HG_VERTEX_X_SLOPERIGHT[1]=+0*m;
global.HG_VERTEX_X_SLOPERIGHT[2]=+1*m;
global.HG_VERTEX_X_SLOPERIGHT[3]=+1*m;
global.HG_VERTEX_X_SLOPERIGHT[4]=+1*m;
global.HG_VERTEX_X_SLOPERIGHT[5]=+0*m;

global.HG_VERTEX_Y_SLOPERIGHT[0]=+1*m;
global.HG_VERTEX_Y_SLOPERIGHT[1]=+1*m;
global.HG_VERTEX_Y_SLOPERIGHT[2]=+1*m;
global.HG_VERTEX_Y_SLOPERIGHT[3]=+0*m;
global.HG_VERTEX_Y_SLOPERIGHT[4]=-1*m;
global.HG_VERTEX_Y_SLOPERIGHT[5]=+0*m;

//SLOPE TOPLEFT:
global.HG_VERTEX_X_SLOPETOPLEFT[0]=-1*m;
global.HG_VERTEX_X_SLOPETOPLEFT[1]=-1*m;
global.HG_VERTEX_X_SLOPETOPLEFT[2]=-1*m;
global.HG_VERTEX_X_SLOPETOPLEFT[3]=+0*m;
global.HG_VERTEX_X_SLOPETOPLEFT[4]=+1*m;
global.HG_VERTEX_X_SLOPETOPLEFT[5]=+0*m;

global.HG_VERTEX_Y_SLOPETOPLEFT[0]=-1*m;
global.HG_VERTEX_Y_SLOPETOPLEFT[1]=+0*m;
global.HG_VERTEX_Y_SLOPETOPLEFT[2]=+1*m;
global.HG_VERTEX_Y_SLOPETOPLEFT[3]=+0*m;
global.HG_VERTEX_Y_SLOPETOPLEFT[4]=-1*m;
global.HG_VERTEX_Y_SLOPETOPLEFT[5]=-1*m;

//SLOPE TOPRIGHT:
global.HG_VERTEX_X_SLOPETOPRIGHT[0]=-1*m;
global.HG_VERTEX_X_SLOPETOPRIGHT[1]=+0*m;
global.HG_VERTEX_X_SLOPETOPRIGHT[2]=+1*m;
global.HG_VERTEX_X_SLOPETOPRIGHT[3]=+1*m;
global.HG_VERTEX_X_SLOPETOPRIGHT[4]=+1*m;
global.HG_VERTEX_X_SLOPETOPRIGHT[5]=+0*m;

global.HG_VERTEX_Y_SLOPETOPRIGHT[0]=-1*m;
global.HG_VERTEX_Y_SLOPETOPRIGHT[1]=+0*m;
global.HG_VERTEX_Y_SLOPETOPRIGHT[2]=+1*m;
global.HG_VERTEX_Y_SLOPETOPRIGHT[3]=+0*m;
global.HG_VERTEX_Y_SLOPETOPRIGHT[4]=-1*m;
global.HG_VERTEX_Y_SLOPETOPRIGHT[5]=-1*m;

//SLAB BOTTOM:
global.HG_VERTEX_X_SLABBOTTOM[0]=-1*m;
global.HG_VERTEX_X_SLABBOTTOM[1]=+0*m;
global.HG_VERTEX_X_SLABBOTTOM[2]=+1*m;
global.HG_VERTEX_X_SLABBOTTOM[3]=+1*m;
global.HG_VERTEX_X_SLABBOTTOM[4]=+0*m;
global.HG_VERTEX_X_SLABBOTTOM[5]=-1*m;

global.HG_VERTEX_Y_SLABBOTTOM[0]=+1*m;
global.HG_VERTEX_Y_SLABBOTTOM[1]=+1*m;
global.HG_VERTEX_Y_SLABBOTTOM[2]=+1*m;
global.HG_VERTEX_Y_SLABBOTTOM[3]=+0*m;
global.HG_VERTEX_Y_SLABBOTTOM[4]=+0*m;
global.HG_VERTEX_Y_SLABBOTTOM[5]=+0*m;

//SLAB TOP:
global.HG_VERTEX_X_SLABTOP[0]=-1*m;
global.HG_VERTEX_X_SLABTOP[1]=+0*m;
global.HG_VERTEX_X_SLABTOP[2]=+1*m;
global.HG_VERTEX_X_SLABTOP[3]=+1*m;
global.HG_VERTEX_X_SLABTOP[4]=+0*m;
global.HG_VERTEX_X_SLABTOP[5]=-1*m;

global.HG_VERTEX_Y_SLABTOP[0]=+0*m;
global.HG_VERTEX_Y_SLABTOP[1]=+0*m;
global.HG_VERTEX_Y_SLABTOP[2]=+0*m;
global.HG_VERTEX_Y_SLABTOP[3]=-1*m;
global.HG_VERTEX_Y_SLABTOP[4]=-1*m;
global.HG_VERTEX_Y_SLABTOP[5]=-1*m;

//SLAB LEFT:
global.HG_VERTEX_X_SLABLEFT[0]=-1*m;
global.HG_VERTEX_X_SLABLEFT[1]=+0*m;
global.HG_VERTEX_X_SLABLEFT[2]=+0*m;
global.HG_VERTEX_X_SLABLEFT[3]=+0*m;
global.HG_VERTEX_X_SLABLEFT[4]=-1*m;
global.HG_VERTEX_X_SLABLEFT[5]=-1*m;

global.HG_VERTEX_Y_SLABLEFT[0]=+1*m;
global.HG_VERTEX_Y_SLABLEFT[1]=+1*m;
global.HG_VERTEX_Y_SLABLEFT[2]=+0*m;
global.HG_VERTEX_Y_SLABLEFT[3]=-1*m;
global.HG_VERTEX_Y_SLABLEFT[4]=-1*m;
global.HG_VERTEX_Y_SLABLEFT[5]=+0*m;

//SLAB RIGHT:
global.HG_VERTEX_X_SLABRIGHT[0]=+0*m;
global.HG_VERTEX_X_SLABRIGHT[1]=+1*m;
global.HG_VERTEX_X_SLABRIGHT[2]=+1*m;
global.HG_VERTEX_X_SLABRIGHT[3]=+1*m;
global.HG_VERTEX_X_SLABRIGHT[4]=+0*m;
global.HG_VERTEX_X_SLABRIGHT[5]=+0*m;

global.HG_VERTEX_Y_SLABRIGHT[0]=+1*m;
global.HG_VERTEX_Y_SLABRIGHT[1]=+1*m;
global.HG_VERTEX_Y_SLABRIGHT[2]=+0*m;
global.HG_VERTEX_Y_SLABRIGHT[3]=-1*m;
global.HG_VERTEX_Y_SLABRIGHT[3]=-1*m;
global.HG_VERTEX_Y_SLABRIGHT[3]=+0*m;

//SLOPE SMALL LEFT:
global.HG_VERTEX_X_SLOPESMLEFT[0]=-1*m;
global.HG_VERTEX_X_SLOPESMLEFT[1]=-1*m;
global.HG_VERTEX_X_SLOPESMLEFT[2]=+0*m;
global.HG_VERTEX_X_SLOPESMLEFT[3]=+1*m;

global.HG_VERTEX_Y_SLOPESMLEFT[0]=+0*m;
global.HG_VERTEX_Y_SLOPESMLEFT[1]=+1*m;
global.HG_VERTEX_Y_SLOPESMLEFT[2]=+1*m;
global.HG_VERTEX_Y_SLOPESMLEFT[3]=+1*m;

//SLOPE SMALL RIGHT:
global.HG_VERTEX_X_SLOPESMRIGHT[0]=-1*m;
global.HG_VERTEX_X_SLOPESMRIGHT[1]=+0*m;
global.HG_VERTEX_X_SLOPESMRIGHT[2]=+1*m;
global.HG_VERTEX_X_SLOPESMRIGHT[3]=+1*m;

global.HG_VERTEX_Y_SLOPESMRIGHT[0]=+1*m;
global.HG_VERTEX_Y_SLOPESMRIGHT[1]=+1*m;
global.HG_VERTEX_Y_SLOPESMRIGHT[2]=+1*m;
global.HG_VERTEX_Y_SLOPESMRIGHT[3]=+0*m;

//SLOPE SMALL TOPLEFT:
global.HG_VERTEX_X_SLOPESMTOPLEFT[0]=+1*m;
global.HG_VERTEX_X_SLOPESMTOPLEFT[1]=+0*m;
global.HG_VERTEX_X_SLOPESMTOPLEFT[2]=-1*m;
global.HG_VERTEX_X_SLOPESMTOPLEFT[3]=-1*m;

global.HG_VERTEX_Y_SLOPESMTOPLEFT[0]=-1*m;
global.HG_VERTEX_Y_SLOPESMTOPLEFT[1]=-1*m;
global.HG_VERTEX_Y_SLOPESMTOPLEFT[2]=-1*m;
global.HG_VERTEX_Y_SLOPESMTOPLEFT[3]=+0*m;

//SLOPE SMALL TOPRIGHT:
global.HG_VERTEX_X_SLOPESMTOPRIGHT[0]=+1*m;
global.HG_VERTEX_X_SLOPESMTOPRIGHT[1]=+1*m;
global.HG_VERTEX_X_SLOPESMTOPRIGHT[2]=+0*m;
global.HG_VERTEX_X_SLOPESMTOPRIGHT[3]=-1*m;

global.HG_VERTEX_Y_SLOPESMTOPRIGHT[0]=+0*m;
global.HG_VERTEX_Y_SLOPESMTOPRIGHT[1]=-1*m;
global.HG_VERTEX_Y_SLOPESMTOPRIGHT[2]=-1*m;
global.HG_VERTEX_Y_SLOPESMTOPRIGHT[3]=-1*m;

//SLOPE SMALL ELEV LEFT: ----------------------
global.HG_VERTEX_X_SLOPESMELEVLEFT[0]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVLEFT[1]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVLEFT[2]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVLEFT[3]=+0*m;
global.HG_VERTEX_X_SLOPESMELEVLEFT[4]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVLEFT[5]=+1*m;

global.HG_VERTEX_Y_SLOPESMELEVLEFT[0]=-1*m;
global.HG_VERTEX_Y_SLOPESMELEVLEFT[1]=+0*m;
global.HG_VERTEX_Y_SLOPESMELEVLEFT[2]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVLEFT[3]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVLEFT[4]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVLEFT[5]=+0*m;

//SLOPE SMALL ELEV RIGHT:
global.HG_VERTEX_X_SLOPESMELEVRIGHT[0]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVRIGHT[1]=+0*m;
global.HG_VERTEX_X_SLOPESMELEVRIGHT[2]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVRIGHT[3]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVRIGHT[4]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVRIGHT[5]=-1*m;

global.HG_VERTEX_Y_SLOPESMELEVRIGHT[0]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVRIGHT[1]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVRIGHT[2]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVRIGHT[3]=+0*m;
global.HG_VERTEX_Y_SLOPESMELEVRIGHT[4]=-1*m;
global.HG_VERTEX_Y_SLOPESMELEVRIGHT[5]=+0*m;

//SLOPE SMALL ELEV TOPLEFT:
global.HG_VERTEX_X_SLOPESMELEVTOPLEFT[0]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPLEFT[1]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPLEFT[2]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPLEFT[3]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPLEFT[4]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPLEFT[5]=+0*m;

global.HG_VERTEX_Y_SLOPESMELEVTOPLEFT[0]=-1*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPLEFT[1]=+0*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPLEFT[2]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPLEFT[3]=+0*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPLEFT[4]=-1*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPLEFT[5]=-1*m;

//SLOPE SMALL ELEV TOPRIGHT:
global.HG_VERTEX_X_SLOPESMELEVTOPRIGHT[0]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPRIGHT[1]=-1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPRIGHT[2]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPRIGHT[3]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPRIGHT[4]=+1*m;
global.HG_VERTEX_X_SLOPESMELEVTOPRIGHT[5]=+0*m;

global.HG_VERTEX_Y_SLOPESMELEVTOPRIGHT[0]=-1*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPRIGHT[1]=+0*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPRIGHT[2]=+1*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPRIGHT[3]=+0*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPRIGHT[4]=-1*m;
global.HG_VERTEX_Y_SLOPESMELEVTOPRIGHT[5]=-1*m;






