///shop_read(Index)
/*
THIS SCRIPT WILL LOAD THE INVENTORY OF THE INDICATED SHOP FROM A STRING PREVIOUSLY
GENERATED BY THE shop_write(...) SCRIPT AND STORED WITHIN global.barter_string.

NOTE: This can and must be used only immediately after using shop_open(), otherwise errors
      will probably be encountered.

argument0 - (Integer) Index of the shop to read.

Returns nothing.
*/
var load_str,temp_str,name,amount;

//Load the specified part of the global.barter_string into load_str:
load_str=string_trim(global.barter_string,"%"+string(argument0)+"b%","%"+string(argument0)+"e%",true);

//Read the string:
while string_length(load_str)>0 begin

 temp_str=string_copy(load_str,1,string_pos("\",load_str));
  load_str=string_delete(load_str,1,string_pos("\",load_str));

 name=string_copy(temp_str,1,string_pos("|",temp_str)-1);
 name=string_trim(name,"[","]",true);
  temp_str=string_delete(temp_str,1,string_pos("|",temp_str));
 amount=string_copy(temp_str,1,string_pos("\",temp_str)-1);
 amount=string_trim(amount,"[","]",true);

 ds_map_add(global.barter_map,name,real(amount));

end;
